name: Contracts

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
      - run: |
          cd contracts
          npm ci
      - name: Run Tests
        run: |
          cd contracts
          npx hardhat node & npx hardhat test
